### Scipy

##### Scipy Sparse Matrix 求和

<p>
scipy.sparse中的稀疏矩阵求和返回值为np.matrix，最低轴数为2，稀疏矩阵的sum函数不会删除求和的轴，squeeze函数也无法删除维度为1的轴

先转换成np.array，再删除维度为1的轴
</p>

In [1]:
from scipy.sparse import csr_matrix
import numpy as np

a = csr_matrix(((np.ones(2)), ([0,1], [1,0])), shape=(2, 2))

In [2]:
a.toarray()

array([[0., 1.],
       [1., 0.]])

In [3]:
type(a.sum(axis=1))

numpy.matrix

In [4]:
a.sum(axis=1).squeeze()

matrix([[1., 1.]])

In [5]:
np.array(a.sum(axis=1)).squeeze()

array([1., 1.])